#!/usr/bin/env fish

echo "Building"
clj -T:build uber

set artifact (ls target | grep "jeopardy.*\.jar")

echo "Uploading $artifact to server"
scp "target/$artifact" jeopardy:~

ssh jeopardy "bash -s" < scripts/server/deploy.sh
