name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Maven deps
      uses: actions/cache@v3.2.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
    - name: Cache Clojure gitlibs
      uses: actions/cache@v3.2.2
      with:
        path: ~/.gitlibs
        key: ${{ runner.os }}-gitlibs
    - name: Setup JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: "19"
        distribution: adopt
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@05cb4bfdf57855f122e75b71e45224775cdfc4a0
      with:
        cli: "1.11.1.1208"
    - name: Build
      run: clojure -T:build uber
